# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  inputs:
    version: '6.x'

- script: dotnet build
  displayName: 'Build projects'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/tests/*Tests/*.fsproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Run tests'
