# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: dotnet build
  displayName: 'Build projects'

- script: |
    dotnet test ./tests/Usemam.Ledger.Backup.Tests/Usemam.Ledger.Backup.Tests.fsproj
    dotnet test ./tests/Usemam.Ledger.Domain.Tests/Usemam.Ledger.Domain.Tests.fsproj
  displayName: 'Run tests'
